#+TITLE:     PHP Public Method
#+AUTHOR:    Rengui Zhao
#+EMAIL:     zrg1390556487@gmail.com
#+LANGUAGE:  cn
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:plain toc:t ltoc:t mouse:underline buttons:0 path:http://cs3.swfc.edu.cn/~20121156044/.org-info.js />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://cs3.swfu.edu.cn/~20121156044/.org-manual.css" />
#+HTML_HEAD: <style>body {font-size:14pt} code {font-weight:bold;font-size:100%; color:darkblue}</style>
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

#+BEGIN_EXPORT HTML
---
layout: post
title: PHP 公共函数
author: zrg
comments: true
description: PHP 公共函数
categories:
- php
tags:
- PHP
photos:
---
#+END_EXPORT

# (setq org-export-html-use-infojs nil)
如果你有任何问题或疑问，请发送Email至zrg1390556487@gmail.com！
# (setq org-export-html-style nil)

* 写在前面
  : 关于PHP的一些公共方法
* 字符串(String)/数组(Array)
** 字符串(String)
*** 字符串长度
    : $strLength=strlen($str);
*** 大小写转换
    : //小写转换为大写
    : strtoupper($str);
    : //大写转换为小写
    : strtolower($str);
*** 字符串截取
    : //截取字符串，取出最有一个字符
    : substr($str,0,-1);
** 数组(Array)
*** string⇌array
    : $array=explode(separator,$string);
    : $pizza = "piece1 piece2 piece3 piece4 piece5 piece6";
    : $pieces = explode(" ", $pizza);
    : echo $pieces[0]; // piece1
    : echo $pieces[1]; // piece2

    : // 数组转化为字符串，implode()
    : $string=implode(glue,$array);
*** array 去除空元素
    : //去除空元素
    : array_filter()
*** array 去除重复元素
    : //去除重复元素
    : array_unique()
*** 判断二维数组是否为空
#+NAME: 判断二维数组是否为空   
 #+BEGIN_SRC emacs-lisp
function array_is_null($arr = null){ 
	if(is_array($arr)){ 
		foreach($arr as $k=>$v){ 
			if($v&&!is_array($v)){ 
				return false; 
			}
			$t = self::array_is_null($v); 
			if(!$t){ 
				return false; 
			} 
		}
		return true; 
	}elseif(!$arr){ 
		return true; 
	}else{ 
		return false; 
	}
}
    #+END_SRC
* 日期(Date)/时间(Time)
** 获取当月天数及当月第一天及最后一天、上月第一天及最后一天
*** 获取上个月第一天及最后一天
    : echo date('Y-m-01', strtotime('-1 month'));
    : echo date('Y-m-t', strtotime('-1 month'));

    : //上个月第一天:
    : echo date('Y-m-d', strtotime(date('Y-m-01') . ' -1 month')); // 计算出本月第一天再减一个月
    : //上个月最后一天:
    : echo date('Y-m-d', strtotime(date('Y-m-01') . ' -1 day')); // 计算出本月第一天再减一天
*** 获取当月第一天及最后一天
    : $BeginDate=date('Y-m-01', strtotime(date("Y-m-d")));
    : echo date('Y-m-d', strtotime("$BeginDate +1 month -1 day"));
*** 获取当前年份、月份、日、天数
    : echo " 本月共有:".date("t")."天";
    : echo " 当前年份".date('Y');
    : echo " 当前月份".date('m');
    : echo " 当前几号".date('d');
** 日期转时间戳，时间戳转日期
   : strtotime('2010-03-24 08:15:42');
   : date('Y-m-d H:i:s', 1156219870);




** 计算日期/时间差
*** 计算已成为会员多少天或距离某活动还剩余多少天?
    #+NAME: 计算函数
    #+BEGIN_SRC emacs-lisp
function get_days_calc($calcTime, $currentTime, $differOrSurplus){
	switch ($differOrSurplus) {
	case 1:
		return round(($currentTime-$calcTime)/3600/24);
		break;
	case 2:
		return round(($calcTime-$currentTime)/3600/24);
		break;
	default:
		return round(($currentTime-$calcTime)/3600/24);
		break;
	}
}
    #+END_SRC
* URL常用函数
** 获取当前URL
   #+NAME: 获取当前URL
   #+BEGIN_SRC emacs-lisp
function getCurrentPageURL()
{
	$pageURL = 'http';
	if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on")
	{
		$pageURL .= "s";
	}
	$pageURL .= "://";
	if ($_SERVER["SERVER_PORT"] != "80")
	{
		$pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"] . $_SERVER["REQUEST_URI"];
	}
	else
	{
		$pageURL .= $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
	}
	return $pageURL;
}
   #+END_SRC
** 请求处理
   #+NAME: 请求处理
   #+BEGIN_SRC emacs-lisp
function curl( $url = '',$method = 'GET',$req_data = false,$header = false,$response_header = false,$exec_time = 5,$connect_time = 5 )
{
	$method = strtoupper( $method );
	$ch = curl_init();
        // 设置请求url
	curl_setopt( $ch,CURLOPT_URL,$url );
        // 设置请求方法,默认执行GET请求，无需设置
	if( 'POST' == $method ){
		curl_setopt( $ch, CURLOPT_POST,1 );
	}elseif( 'GET' != $method ){
		curl_setopt( $ch, CURLOPT_CUSTOMREQUEST,$method );
	}
        // 设置请求头
	if( null != $header && is_array($header) ){
		curl_setopt( $ch,CURLOPT_HTTPHEADER,array_map(function($field,$value){
			return $field . ':' . $value;
		}, array_keys($header), $header) );
	}
        // 设置请请求数据
	if( null != $req_data && 'GET' != $method ){
		if ( is_array($req_data) && !isset($req_data['isfile']) ){
			$req_data = http_build_query($req_data);
		}
		curl_setopt( $ch,CURLOPT_POSTFIELDS,$req_data );
	}
        //设置输出数据中包含http header
	curl_setopt( $ch, CURLOPT_HEADER,$response_header );
	// 将curl_exec()获取的信息以字符串返回，而不是直接输出
	curl_setopt( $ch,CURLOPT_RETURNTRANSFER,true );
        // 允许 cURL 函数执行的最长秒数。
	curl_setopt( $ch,CURLOPT_TIMEOUT,$exec_time );
        //在尝试连接时等待的秒数。设置为0，则无限等待
	curl_setopt( $ch,CURLOPT_CONNECTTIMEOUT,$connect_time );
        // 执行curl请求
	$response = curl_exec($ch);
        //获取状态码
	$status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        //关闭curl回话并释放资源
	curl_close($ch);
        //分离header与body
	if( $response_header ){
		$tmp         = explode("\r\n\r\n", $response);
		$resp_header = $tmp[0];
		$data        = $tmp[1];
	} else {
		$resp_header = null;
		$data        = $response;
	}
	$result['errcode'] = $status;
	$result['header']  = $resp_header;
	$result['data']    = $data;
	return $result;
}
   #+END_SRC
* 文件(File)
** 下载文件
   #+NAME: download file
   #+BEGIN_SRC shell -n 1
   header("Content-type:text/html;charset=utf-8");
   /**
   * 文件下载
   * @param  [type] $file_url [绝对路径，如:$_SERVER['DOCUMENT_ROOT'].'/upload/file/2019/01/18/test.png';]
   * @param  [type] $new_name [指定文件名称]
   * @return [type] [description]
   */
   function downloadFile($file_url,$new_name=''){
   	if(!isset($file_url)||trim($file_url) == ''){
		echo '500';
	}
	//检查文件是否存在
	if(!file_exists($file_url)){
		echo '404';
	}
	$file_name=basename($file_url);
	$file_type=explode('.',$file_url);
	$file_type=$file_type[count($file_type)-1];
	$file_name=trim($new_name=='')?$file_name:urlencode($new_name);
	$file_type=fopen($file_url,'r'); //打开文件
	//输入文件标签
	header("Content-type: application/octet-stream");  
        header("Accept-Ranges: bytes");  
        header("Accept-Length: ".filesize($file_url));  
        header("Content-Disposition: attachment; filename=".$file_name);  
        //输出文件内容  
        echo fread($file_type,filesize($file_url));
	fclose($file_type);
   }
   #+END_SRC
   : 几点注意事项：
   1. header("Content-type:text/html;charset=utf-8")的作用：在服务器响应浏览器的请求时，告诉浏览器以编码格式为UTF-8的编码显示该内容。
   2. 关于file_exists()函数不支持中文路径的问题:因为php函数比较早，不支持中文，所以如果被下载的文件名是中文的话，需要对其进行字符编码转换，否则file_exists()函数不能识别，可以使用iconv()函数进行编码转换。
   3. $file_sub_path() 我使用的是绝对路径，执行效率要比相对路径高。
   4. Header("Content-type: application/octet-stream")的作用：通过这句代码客户端浏览器就能知道服务端返回的文件形式。
   5. Header("Accept-Ranges: bytes")的作用：告诉客户端浏览器返回的文件大小是按照字节进行计算的。
   6. Header("Accept-Length:".$file_size)的作用：告诉浏览器返回的文件大小。
   7. Header("Content-Disposition: attachment; filename=".$file_name)的作用:告诉浏览器返回的文件的名称。
   8. 以上四个Header()是必需的。
   9. fclose($fp)可以把缓冲区内最后剩余的数据输出到磁盘文件中，并释放文件指针和有关的缓冲区
** 参考资料
+ [[http://www.cnblogs.com/hongfei/archive/2012/06/12/2546929.html][Php如何实现下载功能超详细流程分析]]
+ [[https://blog.csdn.net/hj960511/article/details/51837990][php实现当前页面点击下载文件实例]]
* 其他代码片段
** PHP 生成UUID我唯一序列
#+NAME: PHP 生成UUID
#+BEGIN_SRC shell -n 1
function uuid($prefix ='')                                                                                                                            
{                                                                                                                                                     
        $chars = md5(uniqid(mt_rand(), true));                                                                                                        
        $uuid = substr($chars,0,8) . '-';                                                                                                             
        $uuid .= substr($chars,8,4) . '-';                                                                                                            
        $uuid .= substr($chars,12,4) . '-';                                                                                                           
        $uuid .= substr($chars,16,4) . '-';                                                                                                           
        $uuid .= substr($chars,20,12);                                                                                                                
        return $prefix . $uuid;                                                                                                                       
}                                                                                                                                                     
#+END_SRC                                                                                                                                             
: 也可以使用SQL语句生成：insert into Price( Name, UUID, Price) values('FEIFEI_TEST', uuid(), 32); 
